from typing import Protocol, List, Dict, Optional

class ChatRepository(Protocol):
    async def create_conversation(self, access_token: str, docente_id: str, titulo: Optional[str]) -> Dict: ...
    async def list_conversations(self, access_token: str) -> List[Dict]: ...
    async def get_conversation(self, access_token: str, conversation_id: str) -> Optional[Dict]: ...
    async def list_messages(self, access_token: str, conversation_id: str) -> List[Dict]: ...
    async def insert_message(self, access_token: str, conversation_id: str, docente_id: str, role: str, content: str, meta: dict) -> Dict: ...
