from typing import Protocol, List, Dict, Optional

class RecomendacionRepository(Protocol):
    async def crear_recomendacion(self, access_token: str, payload: dict) -> Dict: ...
    async def listar_recomendaciones(self, access_token: str) -> List[Dict]: ...
    async def crear_accion(self, access_token: str, payload: dict) -> Dict: ...
    async def listar_acciones(self, access_token: str, recomendacion_id: str) -> List[Dict]: ...
    async def obtener_recomendacion(self, access_token: str, recomendacion_id: str) -> Optional[Dict]: ...
